import { toMicrounits } from '@/shared/schemas/primitives';
import type { StockItem } from '../../../domain/schemas/inventory';
import type { MercurialeItem } from '../../mercuriales/MercurialeTypes';
import type { SupplierEntity } from '../../core/domain/supplier.types';

export const sampleSuppliers: SupplierEntity[] = [
  {
    id: 'tg',
    tenantId: 'tenant_demo',
    name: 'Transgourmet Rhône-Alpes',
    category: 'dry_goods',
    preferredOrderChannel: 'WHATSAPP',
    contacts: [{ id: 'c1', name: 'Jérôme B.', role: 'commercial', phone: '+33612345678', email: 'jerome@transgourmet.fr', isPrimary: true }],
    francoCts: 25000,
    shippingCostCts: 3000,
    paymentTerms: '30_DAYS',
    paymentMethod: 'SEPA_DEBIT',
    deliverySchedule: { allowedDays: [2, 4, 5], cutOffTime: '22:00', cutOffDaysBefore: 1, deliveryWindow: '06:00-09:00' },
    isActive: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'pomona',
    tenantId: 'tenant_demo',
    name: 'Pomona TerreAzur',
    category: 'produce',
    preferredOrderChannel: 'WHATSAPP',
    contacts: [{ id: 'c2', name: 'Céline V.', role: 'commercial', phone: '+33698765432', email: 'celine@pomona.fr', isPrimary: true }],
    francoCts: 18000,
    shippingCostCts: 2000,
    paymentTerms: '30_DAYS',
    paymentMethod: 'SEPA_DEBIT',
    deliverySchedule: { allowedDays: [1, 2, 3, 4, 5, 6], cutOffTime: '23:30', cutOffDaysBefore: 1, deliveryWindow: '05:00-08:00' },
    isActive: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'fb',
    tenantId: 'tenant_demo',
    name: 'France Boissons',
    category: 'beverages',
    preferredOrderChannel: 'EMAIL_PDF',
    contacts: [{ id: 'c3', name: 'Alexandre M.', role: 'commercial', phone: '+33472001122', email: 'commandes@france-boissons.fr', isPrimary: true }],
    francoCts: 40000,
    shippingCostCts: 4500,
    paymentTerms: '45_DAYS',
    paymentMethod: 'SEPA_DEBIT',
    deliverySchedule: { allowedDays: [2, 5], cutOffTime: '17:00', cutOffDaysBefore: 2, deliveryWindow: '07:00-11:00' },
    isActive: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  }
];

export const sampleStockItems: StockItem[] = [
  {
    id: 'item_entrecote',
    type: 'stockItem',
    name: 'Entrecôte Black Angus',
    quantityInStock: 2,
    threshold: 10,
    criticalThreshold: 4,
    unit: 'kg',
    priceInMicrounits: toMicrounits(22_000_000),
    supplierId: 'tg',
    schemaVersion: 2,
    updatedAt: Date.now(),
  },
  {
    id: 'item_avocat',
    type: 'stockItem',
    name: 'Avocat Hass Calibre 18',
    quantityInStock: 3,
    threshold: 8,
    criticalThreshold: 3,
    unit: 'crate',
    priceInMicrounits: toMicrounits(14_000_000),
    supplierId: 'pomona',
    schemaVersion: 2,
    updatedAt: Date.now(),
  },
  {
    id: 'item_fut_blonde',
    type: 'stockItem',
    name: 'Fût Bière Blonde Artisanale 30L',
    quantityInStock: 1,
    threshold: 4,
    criticalThreshold: 2,
    unit: 'unit',
    priceInMicrounits: toMicrounits(95_000_000),
    supplierId: 'fb',
    schemaVersion: 2,
    updatedAt: Date.now(),
  }
];

export const sampleMercuriales: MercurialeItem[] = [
  {
    id: 'merc_entrecote_tg',
    supplierId: 'tg',
    ingredientId: 'item_entrecote',
    supplierRefCode: 'TG-EA-01',
    name: 'Entrecôte Black Angus',
    packagingLabel: 'Carton 5kg (Sous-vide)',
    packagingQuantity: 5,
    packagingUnit: 'kg',
    conversionFactorToBaseUnit: 5,
    packagePriceHtCts: 11000,
    unitPriceHtCts: 2200,
    vatRatePct: 5.5,
    validFromUtc: Date.now(),
    isAvailable: true,
  },
  {
    id: 'merc_avocat_pomona',
    supplierId: 'pomona',
    ingredientId: 'item_avocat',
    supplierRefCode: 'POM-AV-18',
    name: 'Avocat Hass Calibre 18',
    packagingLabel: 'Colis 4kg (18 pièces)',
    packagingQuantity: 1,
    packagingUnit: 'unit',
    conversionFactorToBaseUnit: 1,
    packagePriceHtCts: 1400,
    unitPriceHtCts: 1400,
    vatRatePct: 5.5,
    validFromUtc: Date.now(),
    isAvailable: true,
  },
  {
    id: 'merc_fut_fb',
    supplierId: 'fb',
    ingredientId: 'item_fut_blonde',
    supplierRefCode: 'FB-BLONDE-30',
    name: 'Fût Bière Blonde Artisanale 30L',
    packagingLabel: 'Fût Inox 30L',
    packagingQuantity: 1,
    packagingUnit: 'unit',
    conversionFactorToBaseUnit: 1,
    packagePriceHtCts: 9500,
    unitPriceHtCts: 9500,
    vatRatePct: 20.0,
    validFromUtc: Date.now(),
    isAvailable: true,
  },
  {
    id: 'merc_huile_tg',
    supplierId: 'tg',
    ingredientId: 'item_huile',
    supplierRefCode: 'TG-OIL-10',
    name: 'Bidon Huile de Tournesol 10L',
    packagingLabel: 'Bidon 10L',
    packagingQuantity: 1,
    packagingUnit: 'l',
    conversionFactorToBaseUnit: 10,
    packagePriceHtCts: 2450,
    unitPriceHtCts: 245,
    vatRatePct: 5.5,
    validFromUtc: Date.now(),
    isAvailable: true,
  }
];
