import { SovereignNode } from '@/shared/nexus-contract';

export interface SEOScore {
    [key: string]: import('@/shared/nexus-contract').SovereignField | undefined;
    overall: number;
    breakdown: {
        titleLength: 'good' | 'warning' | 'error';
        descriptionLength: 'good' | 'warning' | 'error';
        hasH1: boolean;
        hasImageAlt: boolean;
        hasStructuredData: boolean;
        mobileFriendly: boolean;
        pageSpeed: number;
        [key: string]: import('@/shared/nexus-contract').SovereignField | undefined;
    };
    issues: string[];
    recommendations: string[];
}

export interface KeywordStat {
    term: string;
    clicks: number;
    impressions: number;
    avgPosition: number;
}

export interface PageSEO extends SovereignNode {
    pagePath: string;
    pageType: 'home' | 'menu' | 'reservations' | 'contact' | 'blog_post' | 'event' | 'custom';
    meta: {
        title: string;
        titleAutoGenerated: boolean;
        description: string;
        descriptionAutoGenerated: boolean;
        keywords: string[];
        robots: { index: boolean; follow: boolean };
        canonicalUrl: string;
    };
    openGraph: {
        title?: string;
        description?: string;
        image?: string;
        imageAlt?: string;
        type: string;
    };
    score: SEOScore;
    lastUpdated: string;
}

export interface CRM extends SovereignNode {
    firstName: string;
    lastName: string;
    name?: string;
    email?: string;
    phone?: string;
    totalSpentInCents: number;
    lastVisit?: string;
    visitCount?: number;
    segment?: string;
    tags: string[];
}

// Quote moved to master nexus-internal-mapper.ts

export interface MarketingCampaign extends SovereignNode {
    name: string;
    status: 'active' | 'paused' | 'scheduled' | 'completed';
    budgetInCents: number;
    spentInCents: number;
}

export interface PromoCode extends SovereignNode {
    code: string;
    discountPercent?: number;
    discountAmountInCents?: number;
    expiryDate?: string;
    isActive: boolean;
}

export interface CustomerFeedback extends SovereignNode {
    customerId: string;
    customerName: string;
    rating: number;
    comment: string;
    sentiment?: 'positive' | 'neutral' | 'negative';
}

export interface SocialAccount extends SovereignNode {
    platform: 'google' | 'facebook' | 'instagram' | 'tripadvisor' | 'yelp';
    accountId: string;
    accountName: string;
    accessToken?: string;
    refreshToken?: string;
    expiresAt?: string;
    isActive: boolean;
}
