// Définitions déplacées depuis store/marketingAtoms pour casser le cycle
// seo.types <-> marketingAtoms (détecté par sentrux). seo.types est le fichier
// de types canonique ; marketingAtoms les réimporte.
export interface MarketingSegment {
    id: string;
    name: string;
    description: string;
    criteria: Record<string, string> | string;
    estimatedSize: number;
    count?: number;
    color: string;
    createdAt?: string;
    updatedAt?: string;
}

export interface ScheduledPost {
    id: string;
    caption?: string;
    content: string;
    platforms: string[];
    scheduledDate: string;
    scheduledTime: string;
    scheduledFor: string;
    status: 'draft' | 'scheduled' | 'published' | 'failed';
    imageUrl?: string;
    media: { type: string; url: string; };
    createdAt?: string;
    updatedAt?: string;
}

/**
 * SEO & REFERENCING TYPES
 */

export interface SEOScore {
    overall: number;  // 0-100
    breakdown: {
        titleLength: 'good' | 'warning' | 'error';
        descriptionLength: 'good' | 'warning' | 'error';
        hasH1: boolean;
        hasImageAlt: boolean;
        hasStructuredData: boolean;
        mobileFriendly: boolean;
        pageSpeed: number;
    };
    issues: string[];
    recommendations: string[];
}

export interface KeywordStat {
    term: string;
    clicks: number;
    impressions: number;
    avgPosition: number;
}

export interface TrendPoint {
    date: string;
    value: number;
}

export interface StatSource {
    name: string;
    value: number;
    percent: number;
}

export interface PageSEO {
    id: string;
    pagePath: string;
    pageType: 'home' | 'menu' | 'reservations' | 'contact' | 'blog_post' | 'event' | 'custom';

    meta: {
        title: string;
        titleAutoGenerated: boolean;
        description: string;
        descriptionAutoGenerated: boolean;
        keywords: string[];
        robots: {
            index: boolean;
            follow: boolean;
        };
        canonicalUrl: string;
    };

    openGraph: {
        title?: string;
        description?: string;
        image?: string;
        imageAlt?: string;
        type: string;
    };

    score: SEOScore;
    lastAnalyzed?: string;
    lastUpdated: string;
}

export type SEOProfile = SEOConfig;

export interface SEOConfig {
    id: string;
    establishmentId: string;

    site: {
        title: string;
        titleTemplate: string;
        description: string;
        keywords: string[];
        language: string;
        locale: string;
        reservationFunnel?: TrendPoint[];
        weeklyTrend?: TrendPoint[];
        impressions?: number;
        clicks?: number;
        ctr?: number;
        avgPosition?: number;
        topKeywords?: KeywordStat[];
        opened?: number;
        clicked?: number;
        conversions?: number;
    };
    googlePropertyId?: string;
    isVerified?: boolean;
    rating?: number;
    reviewCount?: number;
    googleBusinessConnected?: boolean;
    schemaValidated?: boolean;
    analytics?: { 
        connected: boolean; 
        provider: string;
        visitors?: number;
        pageViews?: number;
        reservations?: number;
        conversionRate?: number;
        sources?: StatSource[];
        devices?: StatSource[];
        topPages?: StatSource[];
        reservationFunnel?: TrendPoint[];
        weeklyTrend?: TrendPoint[];
        impressions?: number;
        clicks?: number;
        ctr?: number;
        avgPosition?: number;
        topKeywords?: KeywordStat[];
        opened?: number;
        clicked?: number;
        conversions?: number;
    };
    name?: string;
    lastSync?: string;
    scheduledPosts?: ScheduledPost[];
    crmSegments?: MarketingSegment[];

    organization: {
        name: string;
        legalName?: string;
        description: string;
        logo: string;
        logoSquare: string;
        contact: {
            telephone: string;
            email: string;
        };
        address: {
            street: string;
            city: string;
            postalCode: string;
            region?: string;
            country: string;
        };
        geo: {
            latitude: number;
            longitude: number;
        };
        socialProfiles: {
            facebook?: string;
            instagram?: string;
            twitter?: string;
            linkedin?: string;
            youtube?: string;
            tiktok?: string;
        };
    };

    restaurant: {
        activityCategories: string[];
        priceRange: '€' | '€€' | '€€€' | '€€€€';
        acceptsReservations: boolean;
        reservationUrl?: string;
        menuUrl?: string;
        openingHours: {
            dayOfWeek: string;
            opens: string | null;
            closes: string | null;
        }[];
        services: {
            dineIn: boolean;
            takeaway: boolean;
            delivery: boolean;
            outdoorSeating: boolean;
            wifi: boolean;
            parking: boolean;
            wheelchairAccessible: boolean;
        };
        aggregateRating?: {
            value: number;
            count: number;
            source: string;
        };
    };

    integrations: {
        googleAnalytics?: { measurementId: string };
        googleTagManager?: { containerId: string };
        googleSearchConsole?: { verified: boolean };
        googleBusinessProfile?: { linked: boolean; placeId?: string; lastSync?: string };
        facebookPixel?: { pixelId: string };
    };

    technical: {
        canonicalDomain: string;
        trailingSlash: boolean;
        robots: { index: boolean; follow: boolean };
        sitemap: { enabled: boolean; frequency: 'daily' | 'weekly' | 'monthly' };
    };

    createdAt: string;
    updatedAt: string;
}
