/**
 * SEO & REFERENCING TYPES
 */

export interface SEOScore {
    overall: number;  // 0-100
    breakdown: {
        titleLength: 'good' | 'warning' | 'error';
        descriptionLength: 'good' | 'warning' | 'error';
        hasH1: boolean;
        hasImageAlt: boolean;
        hasStructuredData: boolean;
        mobileFriendly: boolean;
        pageSpeed: number;
    };
    issues: string[];
    recommendations: string[];
}

export interface PageSEO {
    id: string;
    pagePath: string;
    pageType: 'home' | 'menu' | 'reservations' | 'contact' | 'blog_post' | 'event' | 'custom';

    meta: {
        title: string;
        titleAutoGenerated: boolean;
        description: string;
        descriptionAutoGenerated: boolean;
        keywords: string[];
        robots: {
            index: boolean;
            follow: boolean;
        };
        canonicalUrl: string;
    };

    openGraph: {
        title?: string;
        description?: string;
        image?: string;
        imageAlt?: string;
        type: string;
    };

    score: SEOScore;
    lastAnalyzed?: string;
    lastUpdated: string;
}

export interface SEOConfig {
    id: string;
    establishmentId: string;

    site: {
        title: string;
        titleTemplate: string;
        description: string;
        keywords: string[];
        language: string;
        locale: string;
    };

    organization: {
        name: string;
        legalName?: string;
        description: string;
        logo: string;
        logoSquare: string;
        contact: {
            telephone: string;
            email: string;
        };
        address: {
            street: string;
            city: string;
            postalCode: string;
            region?: string;
            country: string;
        };
        geo: {
            latitude: number;
            longitude: number;
        };
        socialProfiles: {
            facebook?: string;
            instagram?: string;
            twitter?: string;
            linkedin?: string;
            youtube?: string;
            tiktok?: string;
        };
    };

    restaurant: {
        cuisineTypes: string[];
        priceRange: '€' | '€€' | '€€€' | '€€€€';
        acceptsReservations: boolean;
        reservationUrl?: string;
        menuUrl?: string;
        openingHours: {
            dayOfWeek: string;
            opens: string | null;
            closes: string | null;
        }[];
        services: {
            dineIn: boolean;
            takeaway: boolean;
            delivery: boolean;
            outdoorSeating: boolean;
            wifi: boolean;
            parking: boolean;
            wheelchairAccessible: boolean;
        };
        aggregateRating?: {
            value: number;
            count: number;
            source: string;
        };
    };

    integrations: {
        googleAnalytics?: { measurementId: string };
        googleTagManager?: { containerId: string };
        googleSearchConsole?: { verified: boolean };
        googleBusinessProfile?: { linked: boolean; placeId?: string; lastSync?: string };
        facebookPixel?: { pixelId: string };
    };

    technical: {
        canonicalDomain: string;
        trailingSlash: boolean;
        robots: { index: boolean; follow: boolean };
        sitemap: { enabled: boolean; frequency: 'daily' | 'weekly' | 'monthly' };
    };

    createdAt: string;
    updatedAt: string;
}
