import type { IConnectorManifest } from '../types';

export const INTELLIGENCE_CONNECTORS: Record<string, IConnectorManifest> = {
  'meteo-france': {
    id: 'meteo-france', displayName: 'Météo-France', logo: '⛅',
    category: 'weather', pillar: 'intelligence',
    authType: 'api_key',
    fields: [{ key: 'apiKey', label: 'Clé API Météo-France', type: 'password' }],
    verticals: 'all',
    autoActivateFor: ['restaurant', 'hotel'],
    requiredCapability: 'mod_analytics',
    isPremium: false,
  },
  'openweathermap': {
    id: 'openweathermap', displayName: 'OpenWeatherMap', logo: '🌤️',
    category: 'weather', pillar: 'intelligence',
    authType: 'api_key',
    fields: [{ key: 'apiKey', label: 'Clé API OWM', type: 'password' }],
    verticals: 'all',
    autoActivateFor: [],
    requiredCapability: 'mod_analytics',
    isPremium: false,
  },
  'ticketmaster': {
    id: 'ticketmaster', displayName: 'Ticketmaster Events', logo: '🎟️',
    category: 'events', pillar: 'intelligence',
    authType: 'api_key',
    fields: [{ key: 'apiKey', label: 'Clé API Ticketmaster', type: 'password' }],
    verticals: ['restaurant', 'hotel'],
    autoActivateFor: [],
    requiredCapability: 'mod_analytics',
    isPremium: false,
  },
  'claude': {
    id: 'claude', displayName: 'Claude (Anthropic)', logo: '🤖',
    category: 'ai-llm', pillar: 'intelligence',
    authType: 'api_key',
    fields: [{ key: 'apiKey', label: 'Clé API Anthropic', type: 'password', placeholder: 'sk-ant-...' }],
    verticals: 'all',
    autoActivateFor: [],
    requiredCapability: 'mod_agent_dashboard',
    isPremium: true,
  },
  'openai': {
    id: 'openai', displayName: 'ChatGPT (OpenAI)', logo: '💡',
    category: 'ai-llm', pillar: 'intelligence',
    authType: 'api_key',
    fields: [{ key: 'apiKey', label: 'Clé API OpenAI', type: 'password', placeholder: 'sk-...' }],
    verticals: 'all',
    autoActivateFor: [],
    requiredCapability: 'mod_agent_dashboard',
    isPremium: true,
  },
  'mistral': {
    id: 'mistral', displayName: 'Mistral AI', logo: '🇫🇷',
    category: 'ai-llm', pillar: 'intelligence',
    authType: 'api_key',
    fields: [{ key: 'apiKey', label: 'Clé API Mistral', type: 'password' }],
    verticals: 'all',
    autoActivateFor: [],
    requiredCapability: 'mod_agent_dashboard',
    isPremium: true,
  },
  'bofip': {
    id: 'bofip', displayName: 'BOFiP (DGFiP)', logo: '⚖️',
    category: 'ai-legal', pillar: 'intelligence',
    authType: 'none',
    mcp: {
      serverUrl: 'http://localhost:9622',
      toolNames: ['search_bofip', 'get_tva_rates', 'get_fiscal_article'],
    },
    verticals: 'all',
    autoActivateFor: ['restaurant', 'hotel', 'bakery', 'clinic', 'garage', 'retail'],
    requiredCapability: 'mod_accounting_management',
    isPremium: false,
  },
  'dgfip-api': {
    id: 'dgfip-api', displayName: 'API Entreprises (DGFiP)', logo: '🏛️',
    category: 'ai-legal', pillar: 'intelligence',
    authType: 'api_key',
    fields: [{ key: 'token', label: 'Token API Entreprises', type: 'password' }],
    verticals: 'all',
    autoActivateFor: ['restaurant', 'hotel', 'bakery', 'clinic', 'garage', 'retail', 'salon'],
    requiredCapability: 'mod_settings',
    isPremium: false,
  },
};
