import type { IConnectorManifest } from '../types';

export const FINANCE_CONNECTORS: Record<string, IConnectorManifest> = {
  'gmail': {
    id: 'gmail', displayName: 'Gmail / Google Workspace', logo: '📬',
    category: 'communication', pillar: 'finance',
    authType: 'oauth2',
    oauthConfig: {
      authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scopes: [
        'https://www.googleapis.com/auth/gmail.readonly',
        'https://www.googleapis.com/auth/gmail.send',
      ],
      callbackRoute: '/api/auth/google/callback',
    },
    verticals: 'all',
    autoActivateFor: [],
    requiredCapability: 'mod_accounting_management',
    isPremium: false,
  },
  'pennylane': {
    id: 'pennylane', displayName: 'Pennylane', logo: '🪙',
    category: 'accounting', pillar: 'finance',
    authType: 'oauth2',
    oauthConfig: {
      authUrl: 'https://app.pennylane.com/oauth/authorize',
      tokenUrl: 'https://app.pennylane.com/oauth/token',
      scopes: ['accounting:read', 'accounting:write', 'transactions:read'],
      callbackRoute: '/api/connectors/accounting/pennylane/callback',
    },
    verticals: ['restaurant', 'hotel', 'bakery', 'salon', 'clinic', 'retail', 'custom'],
    autoActivateFor: ['restaurant', 'hotel', 'bakery', 'salon', 'clinic', 'retail'],
    requiredCapability: 'mod_accounting_management',
    isPremium: false,
  },
  'quickbooks': {
    id: 'quickbooks', displayName: 'QuickBooks', logo: '📒',
    category: 'accounting', pillar: 'finance',
    authType: 'oauth2',
    oauthConfig: {
      authUrl: 'https://appcenter.intuit.com/connect/oauth2',
      tokenUrl: 'https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer',
      scopes: ['com.intuit.quickbooks.accounting'],
      callbackRoute: '/api/connectors/accounting/quickbooks/callback',
    },
    verticals: ['garage', 'retail', 'custom'],
    autoActivateFor: [],
    requiredCapability: 'mod_accounting_management',
    isPremium: false,
    comingSoon: true,
    roadmapQuarter: 'Q4 2026',
  },
  'xero': {
    id: 'xero', displayName: 'Xero', logo: '🔵',
    category: 'accounting', pillar: 'finance',
    authType: 'oauth2',
    oauthConfig: {
      authUrl: 'https://login.xero.com/identity/connect/authorize',
      tokenUrl: 'https://identity.xero.com/connect/token',
      scopes: ['accounting.transactions', 'accounting.reports.read'],
      callbackRoute: '/api/connectors/accounting/xero/callback',
    },
    verticals: ['retail', 'custom'],
    autoActivateFor: [],
    requiredCapability: 'mod_accounting_management',
    isPremium: false,
    comingSoon: true,
    roadmapQuarter: 'Q4 2026',
  },
  'imap-invoices': {
    id: 'imap-invoices', displayName: 'IMAP (email générique)', logo: '📥',
    category: 'invoices', pillar: 'finance',
    authType: 'api_key',
    fields: [
      { key: 'host', label: 'Serveur IMAP', type: 'text', placeholder: 'imap.example.com' },
      { key: 'user', label: 'Utilisateur', type: 'text' },
      { key: 'password', label: 'Mot de passe', type: 'password' },
    ],
    verticals: 'all',
    autoActivateFor: [],
    requiredCapability: 'mod_accounting_management',
    isPremium: false,
  },
  'stripe': {
    id: 'stripe', displayName: 'Stripe', logo: '💳',
    category: 'payments', pillar: 'finance',
    authType: 'api_key',
    fields: [
      { key: 'secretKey', label: 'Clé secrète', type: 'password', placeholder: 'sk_live_...' },
      { key: 'webhookSecret', label: 'Secret webhook', type: 'password', placeholder: 'whsec_...', optional: true },
    ],
    verticals: 'all',
    autoActivateFor: ['restaurant', 'hotel', 'bakery', 'salon', 'clinic', 'garage', 'retail', 'custom'],
    requiredCapability: 'mod_treasury',
    isPremium: false,
  },
  'gocardless': {
    id: 'gocardless', displayName: 'GoCardless (Open Banking)', logo: '🏦',
    category: 'banking', pillar: 'finance',
    authType: 'api_key',
    fields: [
      { key: 'secretId', label: 'Secret ID', type: 'text', placeholder: 'nordigen-...' },
      { key: 'secretKey', label: 'Secret Key', type: 'password' },
    ],
    verticals: 'all',
    autoActivateFor: ['restaurant', 'hotel', 'retail'],
    requiredCapability: 'mod_treasury',
    isPremium: false,
  },
};
