import type { IConnectorManifest } from '../types';

export const OPS_CONNECTORS: Record<string, IConnectorManifest> = {
  'zenchef': {
    id: 'zenchef', displayName: 'Zenchef', logo: '🗓️',
    category: 'reservations', pillar: 'ops',
    authType: 'api_key',
    fields: [{ key: 'apiKey', label: 'Clé API', type: 'password', placeholder: 'zc_live_...' }],
    verticals: ['restaurant', 'hotel', 'bakery'],
    autoActivateFor: ['restaurant'],
    requiredCapability: 'mod_reservations',
    isPremium: false,
  },
  'thefork': {
    id: 'thefork', displayName: 'TheFork', logo: '🍴',
    category: 'reservations', pillar: 'ops',
    authType: 'oauth2',
    oauthConfig: {
      authUrl: 'https://manager.thefork.com/oauth/authorize',
      tokenUrl: 'https://manager.thefork.com/oauth/token',
      scopes: ['reservations:read', 'reservations:write'],
      callbackRoute: '/api/connectors/reservations/thefork/callback',
    },
    verticals: ['restaurant', 'hotel'],
    autoActivateFor: [],
    requiredCapability: 'mod_reservations',
    isPremium: false,
  },
  'widget-reservations': {
    id: 'widget-reservations', displayName: 'Widget natif', logo: '📋',
    category: 'reservations', pillar: 'ops',
    authType: 'none',
    verticals: 'all',
    autoActivateFor: ['restaurant', 'hotel', 'bakery', 'clinic', 'salon', 'garage', 'retail', 'custom'],
    requiredCapability: 'mod_reservations',
    isPremium: false,
  },
  'uber-eats': {
    id: 'uber-eats', displayName: 'Uber Eats', logo: '🛵',
    category: 'delivery', pillar: 'ops',
    authType: 'oauth2',
    oauthConfig: {
      authUrl: 'https://login.uber.com/oauth/v2/authorize',
      tokenUrl: 'https://login.uber.com/oauth/v2/token',
      scopes: ['eats.store', 'eats.order'],
      callbackRoute: '/api/connectors/delivery/webhook/ubereats',
    },
    verticals: ['restaurant', 'bakery'],
    autoActivateFor: ['restaurant'],
    requiredCapability: 'mod_pos',
    isPremium: false,
  },
  'deliveroo': {
    id: 'deliveroo', displayName: 'Deliveroo', logo: '🦘',
    category: 'delivery', pillar: 'ops',
    authType: 'api_key',
    fields: [{ key: 'apiKey', label: 'Clé API Deliveroo', type: 'password' }],
    verticals: ['restaurant', 'bakery'],
    autoActivateFor: [],
    requiredCapability: 'mod_pos',
    isPremium: false,
  },
  'just-eat': {
    id: 'just-eat', displayName: 'Just Eat', logo: '🍕',
    category: 'delivery', pillar: 'ops',
    authType: 'api_key',
    fields: [{ key: 'apiKey', label: 'Clé API Just Eat', type: 'password' }],
    verticals: ['restaurant', 'bakery'],
    autoActivateFor: [],
    requiredCapability: 'mod_pos',
    isPremium: false,
  },
  'click-collect': {
    id: 'click-collect', displayName: 'Click & Collect natif', logo: '🏪',
    category: 'delivery', pillar: 'ops',
    authType: 'none',
    verticals: 'all',
    autoActivateFor: ['restaurant', 'bakery', 'retail'],
    requiredCapability: 'mod_pos',
    isPremium: false,
  },
  'booking-com': {
    id: 'booking-com', displayName: 'Booking.com', logo: '🏨',
    category: 'marketplace', pillar: 'ops',
    authType: 'api_key',
    fields: [
      { key: 'hotelId', label: 'Hotel ID', type: 'text' },
      { key: 'apiKey', label: 'Clé API', type: 'password' },
    ],
    verticals: ['hotel'],
    autoActivateFor: ['hotel'],
    requiredCapability: 'mod_pms',
    isPremium: false,
  },
  'mews-pms': {
    id: 'mews-pms', displayName: 'Mews PMS', logo: '🛎️',
    category: 'vertical-specific', pillar: 'ops',
    authType: 'api_key',
    fields: [{ key: 'clientToken', label: 'Client Token', type: 'password' }],
    verticals: ['hotel'],
    autoActivateFor: [],
    requiredCapability: 'mod_pms',
    isPremium: true,
    comingSoon: true,
    roadmapQuarter: 'Q4 2026',
  },
  'treatwell': {
    id: 'treatwell', displayName: 'Treatwell', logo: '💈',
    category: 'marketplace', pillar: 'ops',
    authType: 'oauth2',
    oauthConfig: {
      authUrl: 'https://api.treatwell.com/oauth/authorize',
      tokenUrl: 'https://api.treatwell.com/oauth/token',
      scopes: ['appointments:read', 'appointments:write'],
      callbackRoute: '/api/connectors/reservations/treatwell/callback',
    },
    verticals: ['salon'],
    autoActivateFor: [],
    requiredCapability: 'mod_reservations',
    isPremium: false,
    comingSoon: true,
    roadmapQuarter: 'Q4 2026',
  },
  'fresha': {
    id: 'fresha', displayName: 'Fresha', logo: '✂️',
    category: 'marketplace', pillar: 'ops',
    authType: 'api_key',
    fields: [{ key: 'apiKey', label: 'Clé API Fresha', type: 'password' }],
    verticals: ['salon'],
    autoActivateFor: [],
    requiredCapability: 'mod_reservations',
    isPremium: false,
    comingSoon: true,
    roadmapQuarter: 'Q4 2026',
  },
  'doctolib': {
    id: 'doctolib', displayName: 'Doctolib', logo: '🩺',
    category: 'vertical-specific', pillar: 'ops',
    authType: 'api_key',
    fields: [{ key: 'apiKey', label: 'Clé API Doctolib', type: 'password' }],
    verticals: ['clinic'],
    autoActivateFor: ['clinic'],
    requiredCapability: 'mod_reservations',
    isPremium: true,
  },
};
