import type { IConnectorManifest } from '../types';

export const COMMERCE_CONNECTORS: Record<string, IConnectorManifest> = {
  'google-business': {
    id: 'google-business', displayName: 'Google My Business', logo: '⭐',
    category: 'reviews', pillar: 'commerce',
    authType: 'oauth2',
    oauthConfig: {
      authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scopes: ['https://www.googleapis.com/auth/business.manage'],
      callbackRoute: '/api/auth/google/callback',
    },
    verticals: 'all',
    autoActivateFor: ['restaurant', 'hotel', 'bakery', 'salon', 'clinic', 'garage', 'retail'],
    requiredCapability: 'mod_analytics',
    isPremium: false,
  },
  'tripadvisor': {
    id: 'tripadvisor', displayName: 'TripAdvisor', logo: '🦉',
    category: 'reviews', pillar: 'commerce',
    authType: 'api_key',
    fields: [{ key: 'apiKey', label: 'Clé API TripAdvisor', type: 'password' }],
    verticals: ['restaurant', 'hotel'],
    autoActivateFor: [],
    requiredCapability: 'mod_analytics',
    isPremium: false,
  },
  'brevo': {
    id: 'brevo', displayName: 'Brevo (Sendinblue)', logo: '📧',
    category: 'emailing', pillar: 'commerce',
    authType: 'api_key',
    fields: [{ key: 'apiKey', label: 'Clé API Brevo', type: 'password', placeholder: 'xkeysib-...' }],
    verticals: 'all',
    autoActivateFor: ['restaurant', 'hotel', 'bakery', 'salon', 'retail'],
    requiredCapability: 'mod_omnichannel',
    isPremium: false,
  },
  'whatsapp-business': {
    id: 'whatsapp-business', displayName: 'WhatsApp Business', logo: '💬',
    category: 'communication', pillar: 'commerce',
    authType: 'api_key',
    fields: [
      { key: 'accessToken', label: 'Token accès Meta', type: 'password' },
      { key: 'phoneNumberId', label: 'ID Numéro', type: 'text' },
    ],
    verticals: 'all',
    autoActivateFor: [],
    requiredCapability: 'mod_omnichannel',
    isPremium: false,
  },
  'shopify': {
    id: 'shopify', displayName: 'Shopify', logo: '🛍️',
    category: 'ecommerce', pillar: 'commerce',
    authType: 'oauth2',
    oauthConfig: {
      authUrl: 'https://{shop}.myshopify.com/admin/oauth/authorize',
      tokenUrl: 'https://{shop}.myshopify.com/admin/oauth/access_token',
      scopes: ['read_orders', 'write_orders', 'read_products', 'write_products'],
      callbackRoute: '/api/connectors/ecommerce/shopify/callback',
    },
    verticals: ['retail', 'bakery'],
    autoActivateFor: [],
    requiredCapability: 'mod_pos',
    isPremium: false,
    comingSoon: true,
    roadmapQuarter: 'Q4 2026',
  },
  'google-shopping': {
    id: 'google-shopping', displayName: 'Google Shopping', logo: '🛒',
    category: 'ecommerce', pillar: 'commerce',
    authType: 'oauth2',
    oauthConfig: {
      authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scopes: ['https://www.googleapis.com/auth/content'],
      callbackRoute: '/api/connectors/ecommerce/google-shopping/callback',
    },
    verticals: ['retail', 'bakery'],
    autoActivateFor: [],
    requiredCapability: 'mod_pos',
    isPremium: false,
    comingSoon: true,
    roadmapQuarter: 'Q4 2026',
  },
};
