import type { PageKey, PageSettingConfig } from "@nexus/contracts/permissions.types";

export const PAGE_SETTINGS: Record<PageKey, { title: string; settings: PageSettingConfig[] }> = {
    dashboard: {
        title: "Paramètres du Tableau de Bord",
        settings: [
            { key: "show_ca", label: "Afficher le CA", group: "logic", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "period_default", label: "Période par défaut", group: "logic", type: "select", options: [{ value: "day", label: "Jour" }, { value: "week", label: "Semaine" }, { value: "month", label: "Mois" }], roles: ["admin", "directeur", "manager"] },
            { key: "ca_target", label: "Objectif CA journalier (€)", group: "logic", type: "number", min: 0, max: 100000, roles: ["admin", "directeur"] },
            { key: "tickets_target", label: "Objectif tickets/jour", group: "logic", type: "number", min: 0, max: 500, roles: ["admin", "directeur"] },
            { key: "occupation_target", label: "Objectif occupation (%)", group: "logic", type: "number", min: 0, max: 100, roles: ["admin", "directeur"] },
            { key: "show_staff_metrics", label: "Afficher métriques équipe", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "show_weather_widget", label: "Afficher météo", group: "style", type: "toggle", roles: ["admin", "directeur", "manager", "serveur", "hotesse"] },
            { key: "auto_refresh_interval", label: "Rafraîchissement auto (sec)", group: "logic", type: "number", min: 10, max: 300, roles: ["admin", "directeur", "manager"] },
            { key: "show_reservations_preview", label: "Aperçu réservations à venir", group: "logic", type: "toggle", roles: ["admin", "directeur", "manager", "hotesse"] },
        ],
    },
    vanguard: {
        title: "Paramètres Vanguard",
        settings: [
            { key: "max_concurrent_sessions", label: "Appareils simultanés par utilisateur", description: "1 = un serveur ne peut pas utiliser deux tablettes en même temps.", group: "logic", type: "number", min: 1, max: 5, roles: ["admin"] },
        ]
    },
    franchise: {
        title: "Paramètres Réseau & Franchise",
        settings: [
            { key: "allow_transfers", label: "Autoriser les transferts de stock", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "auto_approve_transfers", label: "Validation automatique des transferts", group: "logic", type: "toggle", roles: ["admin"] },
        ]
    },
    floor_plan: {
        title: "Paramètres du Plan de Salle",
        settings: [
            { key: "show_grid", label: "Afficher la grille", group: "style", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "grid_size", label: "Taille de grille", group: "style", type: "select", options: [{ value: "20", label: "20px" }, { value: "40", label: "40px" }, { value: "60", label: "60px" }], roles: ["admin", "directeur"] },
            { key: "snap_to_grid", label: "Alignement grille", group: "logic", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "default_view", label: "Vue par défaut", group: "style", type: "select", options: [{ value: "2d", label: "2D" }, { value: "3d", label: "3D" }], roles: ["admin", "directeur", "manager"] },
            { key: "lock_zones", label: "Verrouiller les zones", group: "logic", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "table_numbering_auto", label: "Numérotation auto tables", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "show_server_zones", label: "Afficher zones serveurs", group: "style", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "show_capacity_limits", label: "Afficher limites capacité", group: "style", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "edit_mode_locked", label: "Verrouiller mode édition", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
        ],
    },
    reservations: {
        title: "Paramètres des Réservations",
        settings: [
            { key: "default_view", label: "Vue par défaut", group: "style", type: "select", options: [{ value: "day", label: "Jour" }, { value: "week", label: "Semaine" }, { value: "list", label: "Liste" }], roles: ["admin", "directeur", "manager", "hotesse"] },
            { key: "default_duration", label: "Durée par défaut (min)", group: "logic", type: "select", options: [{ value: "60", label: "60 min" }, { value: "90", label: "90 min" }, { value: "120", label: "120 min" }], roles: ["admin", "directeur"] },
            { key: "min_advance", label: "Délai min avant résa (h)", group: "logic", type: "number", min: 0, max: 48, roles: ["admin", "directeur"] },
            { key: "max_advance", label: "Délai max avant résa (j)", group: "logic", type: "number", min: 1, max: 90, roles: ["admin", "directeur"] },
            { key: "auto_confirm", label: "Confirmation automatique", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "allow_overbooking", label: "Autoriser l'overbooking", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "noshow_delay", label: "Délai no-show (min)", group: "logic", type: "number", min: 5, max: 60, roles: ["admin", "directeur", "manager"] },
            { key: "sms_confirmation", label: "Confirmation par SMS", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "email_confirmation", label: "Confirmation par email", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "reminder_hours_before", label: "Rappel X heures avant", group: "logic", type: "number", min: 1, max: 48, roles: ["admin", "directeur"] },
            { key: "vip_priority", label: "Réservation VIP prioritaire", group: "logic", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "auto_assign_tables", label: "Attribution auto tables", group: "logic", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "waitlist_enabled", label: "Liste d'attente activée", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "turnover_factor_per_guest_pct", label: "Allongement par convive au-delà de 2 (%)", description: "Modèle de rotation de table (DF-C5).", group: "logic", type: "number", min: 0, max: 30, roles: ["admin", "directeur"] },
            { key: "turnover_kds_impact_max_pct", label: "Impact max du retard cuisine (%)", description: "Impact de la surchauffe KDS sur la rotation (DF-C6).", group: "logic", type: "number", min: 0, max: 100, roles: ["admin", "directeur"] },
        ],
    },
    pos: {
        title: "Paramètres de la Caisse & Vente",
        settings: [
            { key: "service_mode", label: "Mode service", group: "logic", type: "select", options: [{ value: "table", label: "Table" }, { value: "counter", label: "Comptoir" }, { value: "mixed", label: "Mixte" }], roles: ["admin", "directeur"] },
            { key: "button_size", label: "Taille des boutons", group: "style", type: "select", options: [{ value: "small", label: "Petit" }, { value: "medium", label: "Moyen" }, { value: "large", label: "Grand" }], roles: ["admin", "directeur", "manager"] },
            { key: "show_images", label: "Afficher les images", group: "style", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "auto_print", label: "Impression auto ticket", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "tips_enabled", label: "Pourboires activés", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "sound_enabled", label: "Sons activés", group: "style", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "max_discount_no_pin", label: "Remise max sans code (%)", group: "logic", type: "number", min: 0, max: 50, roles: ["admin", "directeur"] },
            { key: "split_bill_enabled", label: "Addition divisée", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "quick_pay_buttons", label: "Boutons paiement rapide", group: "style", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "cash_drawer_auto_open", label: "Ouverture auto caisse", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "require_table_selection", label: "Table obligatoire", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "show_stock_level", label: "Afficher niveau stock", group: "style", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "keyboard_shortcuts", label: "Raccourcis clavier", group: "style", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "loyalty_points_visible", label: "Points fidélité visibles", group: "style", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "table_lock_ttl_sec", label: "Durée de réservation d'une table (secondes)", description: "Temps avant expiration du verrou table (DF-A1).", group: "logic", type: "number", min: 30, max: 600, roles: ["admin", "directeur", "manager", "chef_rang"] },
            { key: "warn_no_terminal", label: "Avertir si aucun TPE n'est configuré", description: "Alerte visuelle au démarrage de service (DF-A2).", group: "logic", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "delivery_min_address_score", label: "Score d'adresse livraison minimal", description: "Score d'adresse requis pour acceptation automatique (DF-M2).", group: "logic", type: "number", min: 0, max: 100, roles: ["admin", "directeur", "manager"] },
            { key: "failover_group_only", label: "Secours imprimante limité au groupe (cuisine/bar)", description: "Évite qu'un bon cuisine sorte au bar (DF-D1).", group: "logic", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "on_print_failure", label: "Comportement si échec d'impression", description: "Gestion d'incident NF525 après validation fiscale (DF-D3).", group: "logic", type: "select", options: [{ value: "queue", label: "Mettre en file et alerter" }, { value: "block", label: "Bloquer la vente" }, { value: "continue", label: "Continuer sans ticket" }], roles: ["admin", "directeur"] },
        ],
    },
    kitchen: {
        title: "Paramètres Cuisine & Recettes",
        settings: [
            { key: "default_unit", label: "Unité par défaut", group: "logic", type: "select", options: [{ value: "g", label: "Grammes" }, { value: "kg", label: "Kilos" }, { value: "L", label: "Litres" }, { value: "portions", label: "Portions" }], roles: ["admin", "directeur", "chef_cuisinier"] },
            { key: "default_yield", label: "Rendement par défaut", group: "logic", type: "number", min: 1, max: 100, roles: ["admin", "directeur", "chef_cuisinier"] },
            { key: "show_costs_to_cooks", label: "Afficher coûts aux cuisiniers", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "show_margins", label: "Afficher les marges", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "default_waste_percent", label: "% perte par défaut", group: "logic", type: "number", min: 0, max: 50, roles: ["admin", "directeur", "chef_cuisinier"] },
            { key: "show_nutrition", label: "Afficher nutrition", group: "style", type: "toggle", roles: ["admin", "directeur", "chef_cuisinier"] },
            { key: "show_allergens", label: "Afficher allergènes", group: "style", type: "toggle", roles: ["admin", "directeur", "chef_cuisinier"] },
            { key: "target_food_cost", label: "% food cost cible", group: "logic", type: "number", min: 10, max: 60, roles: ["admin", "directeur"] },
            { key: "recipe_scaling_enabled", label: "Mise à l'échelle recettes", group: "logic", type: "toggle", roles: ["admin", "directeur", "chef_cuisinier"] },
            { key: "ingredient_substitution_alerts", label: "Alertes substitution ingrédients", group: "logic", type: "toggle", roles: ["admin", "directeur", "chef_cuisinier"] },
            { key: "batch_cooking_mode", label: "Mode production par lots", group: "logic", type: "toggle", roles: ["admin", "directeur", "chef_cuisinier"] },
            { key: "print_recipe_cards", label: "Impression fiches recettes", group: "style", type: "toggle", roles: ["admin", "directeur", "chef_cuisinier"] },
            { key: "plating_guides", label: "Guides de dressage", group: "style", type: "toggle", roles: ["admin", "directeur", "chef_cuisinier"] },
        ],
    },
    kds: {
        title: "Paramètres KDS & Production",
        settings: [
            { key: "columns", label: "Nombre de colonnes", group: "style", type: "select", options: [{ value: "2", label: "2" }, { value: "3", label: "3" }, { value: "4", label: "4" }, { value: "5", label: "5" }], roles: ["admin", "directeur", "manager"] },
            { key: "sort_mode", label: "Tri des commandes", group: "logic", type: "select", options: [{ value: "fifo", label: "FIFO" }, { value: "priority", label: "Priorité" }, { value: "type", label: "Type" }], roles: ["admin", "directeur", "manager"] },
            { key: "alert_delay", label: "Alerte retard (min)", group: "logic", type: "number", min: 5, max: 60, roles: ["admin", "directeur"] },
            { key: "overheat_threshold_min", label: "Seuil de surchauffe cuisine (min)", description: "Au-delà, le bridage automatique s'active (DF-B1).", group: "logic", type: "number", min: 5, max: 60, roles: ["admin", "directeur", "chef_cuisinier"] },
            { key: "throttle_max_orders", label: "Commandes max pendant le bridage", description: "Capacité maximale admise par tranche de régulation (DF-B2).", group: "logic", type: "number", min: 1, max: 20, roles: ["admin", "directeur", "chef_cuisinier"] },
            { key: "throttle_duration_sec", label: "Durée du bridage (secondes)", group: "logic", type: "number", min: 60, max: 3600, roles: ["admin", "directeur", "chef_cuisinier"] },
            { key: "throttle_enabled", label: "Activer le bridage automatique", description: "Permet de débrider en urgence pendant un coup de feu (DF-B2).", group: "logic", type: "toggle", roles: ["admin", "directeur", "chef_cuisinier"] },
            { key: "audio_volume", label: "Volume des alertes cuisine (%)", group: "style", type: "number", min: 0, max: 100, roles: ["admin", "directeur", "chef_cuisinier", "cuisinier"] },
            { key: "sound_new_order", label: "Son nouvelle commande", group: "style", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "sound_alert", label: "Son alerte retard", group: "style", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "show_table", label: "Afficher table/client", group: "style", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "highlight_allergies", label: "Signaler allergies", group: "style", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "bump_confirmation", label: "Confirmation bump", group: "logic", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "order_age_colors", label: "Couleurs selon ancienneté", group: "style", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "consolidate_items", label: "Regrouper items identiques", group: "logic", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "prep_time_estimates", label: "Estimation temps préparation", group: "logic", type: "toggle", roles: ["admin", "directeur", "chef_cuisinier"] },
        ],
    },
    inventory: {
        title: "Paramètres Inventaire & Approvisionnement",
        settings: [
            { key: "low_stock_threshold", label: "Seuil stock bas", group: "logic", type: "number", min: 1, max: 100, roles: ["admin", "directeur", "manager"] },
            { key: "critical_threshold", label: "Seuil critique", group: "logic", type: "number", min: 1, max: 50, roles: ["admin", "directeur"] },
            { key: "default_unit", label: "Unité par défaut", group: "logic", type: "select", options: [{ value: "kg", label: "kg" }, { value: "L", label: "L" }, { value: "units", label: "Unités" }], roles: ["admin", "directeur", "manager"] },
            { key: "valuation_method", label: "Méthode valorisation", group: "logic", type: "select", options: [{ value: "fifo", label: "FIFO" }, { value: "lifo", label: "LIFO" }, { value: "weighted", label: "Moy. pondérée" }], roles: ["admin", "directeur"] },
            { key: "show_valuation", label: "Afficher valeur stock", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "auto_order_enabled", label: "Commande auto activée", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "supplier_comparison", label: "Comparaison fournisseurs", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "barcode_scanning", label: "Scan codes-barres", group: "logic", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "lot_tracking", label: "Traçabilité lots", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "expiry_first_out", label: "DLC prioritaire sortie", group: "logic", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "waste_tracking_mandatory", label: "Suivi pertes obligatoire", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "count_frequency_days", label: "Fréquence inventaire (jours)", group: "logic", type: "number", min: 1, max: 30, roles: ["admin", "directeur"] },
            { key: "supplier_cutoff_warning_min", label: "Alerte avant clôture fournisseur (min)", group: "logic", type: "number", min: 15, max: 240, roles: ["admin", "directeur", "chef_cuisinier"] },
            { key: "commodity_surge_alert_pct", label: "Flambée de cours — seuil d'alerte (%)", group: "logic", type: "number", min: 5, max: 50, roles: ["admin", "directeur", "chef_cuisinier"] },
            { key: "food_cost_weight_pct", label: "Poids food cost dans l'ajustement prix (%)", description: "Pondération de la hausse des cours sur la recommandation de prix menu (DF-J3).", group: "logic", type: "number", min: 10, max: 60, roles: ["admin", "directeur"] },
            { key: "ocr_confidence_threshold", label: "Confiance OCR minimale (%)", description: "En dessous, la facture part en validation manuelle (DF-J4).", group: "logic", type: "number", min: 60, max: 99, roles: ["admin", "directeur", "comptable"] },
            { key: "weather_procurement_temp_c", label: "Température déclenchant ajustement météo (°C)", group: "logic", type: "number", min: 15, max: 40, roles: ["admin", "directeur", "chef_cuisinier"] },
            { key: "weather_procurement_boost_pct", label: "Ajustement météo produits frais (%)", group: "logic", type: "number", min: 0, max: 50, roles: ["admin", "directeur", "chef_cuisinier"] },
        ],
    },
    storage_map: {
        title: "Paramètres Stockage",
        settings: [
            { key: "dlc_alert_days", label: "Alerte DLC (jours avant)", group: "logic", type: "number", min: 1, max: 14, roles: ["admin", "directeur", "manager"] },
            { key: "compact_view", label: "Vue compacte", group: "style", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "temperature_alerts", label: "Alertes température", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "zone_capacity_display", label: "Afficher capacité zones", group: "style", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "fifo_enforcement", label: "Forcer FIFO", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
        ],
    },
    customer: {
        title: "Paramètres Clients & Fidélité",
        settings: [
            { key: "default_view", label: "Vue par défaut", group: "style", type: "select", options: [{ value: "list", label: "Liste" }, { value: "cards", label: "Cartes" }, { value: "table", label: "Tableau" }], roles: ["admin", "directeur", "manager"] },
            { key: "required_phone", label: "Téléphone obligatoire", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "required_email", label: "Email obligatoire", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "retention_months", label: "Rétention données (mois)", group: "logic", type: "number", min: 6, max: 120, roles: ["admin"] },
            { key: "vip_auto_upgrade", label: "Upgrade VIP auto", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "vip_threshold_visits", label: "Seuil visites VIP", group: "logic", type: "number", min: 1, max: 50, roles: ["admin", "directeur"] },
            { key: "vip_threshold_spend", label: "Seuil dépenses VIP (€)", group: "logic", type: "number", min: 100, max: 10000, roles: ["admin", "directeur"] },
            { key: "loyalty_points_per_euro", label: "Points de fidélité par euro dépensé", description: "Cœur économique du programme de fidélité (DF-K1).", group: "logic", type: "number", min: 0, max: 10, roles: ["admin", "directeur"] },
            { key: "quote_base_score", label: "Score de base d'un devis", group: "logic", type: "number", min: 0, max: 100, roles: ["admin", "directeur"] },
            { key: "birthday_reminders", label: "Rappels anniversaires", group: "logic", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "feedback_request_enabled", label: "Demande feedback auto", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "gdpr_consent_required", label: "Consentement RGPD requis", group: "logic", type: "toggle", roles: ["admin"] },
        ],
    },
    staff: {
        title: "Paramètres Équipe",
        settings: [
            { key: "show_salaries_to_managers", label: "Salaires visibles aux managers", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "doc_expiry_alert_days", label: "Alerte expiration docs (jours)", group: "logic", type: "number", min: 7, max: 90, roles: ["admin", "directeur"] },
            { key: "timesheet_approval_required", label: "Approbation pointages", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "overtime_auto_calculate", label: "Calcul auto heures sup", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "photo_id_required", label: "Photo ID obligatoire", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "skills_matrix_enabled", label: "Matrice compétences", group: "style", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "performance_reviews_enabled", label: "Évaluations performance", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "training_tracking", label: "Suivi formations", group: "logic", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "contract_alerts", label: "Alertes contrats", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
        ],
    },
    planning: {
        title: "Paramètres Planning",
        settings: [
            { key: "week_start", label: "Premier jour semaine", group: "logic", type: "select", options: [{ value: "monday", label: "Lundi" }, { value: "sunday", label: "Dimanche" }], roles: ["admin", "directeur"] },
            { key: "default_view", label: "Vue par défaut", group: "style", type: "select", options: [{ value: "day", label: "Jour" }, { value: "week", label: "Semaine" }, { value: "month", label: "Mois" }], roles: ["admin", "directeur", "manager"] },
            { key: "max_hours_day", label: "Max heures/jour", group: "logic", type: "number", min: 6, max: 12, roles: ["admin", "directeur"] },
            { key: "max_hours_week", label: "Max heures/semaine", group: "logic", type: "number", min: 20, max: 48, roles: ["admin", "directeur"] },
            { key: "min_rest_hours", label: "Repos min entre shifts (h)", group: "logic", type: "number", min: 8, max: 14, roles: ["admin", "directeur"] },
            { key: "notify_on_publish", label: "Notifier à la publication", group: "logic", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "require_swap_approval", label: "Valider les échanges", group: "logic", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "overtime_enabled", label: "Heures sup autorisées", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "auto_schedule_enabled", label: "Planification auto (IA)", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "availability_required", label: "Disponibilités obligatoires", group: "logic", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "shift_templates", label: "Modèles de shifts", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "labor_cost_preview", label: "Aperçu coût main d'oeuvre", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "conflict_detection", label: "Détection conflits", group: "logic", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "mobile_clock_in", label: "Pointage mobile", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
        ],
    },
    leaves: {
        title: "Paramètres Congés",
        settings: [
            { key: "require_approval", label: "Approbation requise", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "min_advance_days", label: "Délai min demande (jours)", group: "logic", type: "number", min: 1, max: 30, roles: ["admin", "directeur"] },
            { key: "max_concurrent_leaves", label: "Max congés simultanés", group: "logic", type: "number", min: 1, max: 10, roles: ["admin", "directeur"] },
            { key: "blackout_dates_enabled", label: "Dates bloquées", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "auto_approve_short_leaves", label: "Auto-approbation congés courts", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "carry_over_days", label: "Report jours congés", group: "logic", type: "number", min: 0, max: 30, roles: ["admin", "directeur"] },
            { key: "sick_leave_certificate", label: "Justificatif maladie", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "leave_calendar_public", label: "Calendrier congés public", group: "style", type: "toggle", roles: ["admin", "directeur", "manager"] },
        ],
    },
    finance: {
        title: "Paramètres Finance & Rapprochement",
        settings: [
            { key: "fiscal_year_start", label: "Début exercice fiscal", group: "logic", type: "text", roles: ["admin"] },
            { key: "default_payment_terms", label: "Conditions paiement (jours)", group: "logic", type: "number", min: 0, max: 90, roles: ["admin", "directeur", "comptable"] },
            { key: "invoice_prefix", label: "Préfixe factures", group: "logic", type: "text", roles: ["admin", "directeur"] },
            { key: "export_format", label: "Format export", group: "style", type: "select", options: [{ value: "pdf", label: "PDF" }, { value: "csv", label: "CSV" }, { value: "excel", label: "Excel" }], roles: ["admin", "directeur", "comptable"] },
            { key: "auto_invoice_generation", label: "Génération auto factures", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "bank_reconciliation_auto", label: "Rapprochement bancaire auto", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "auto_reconcile_score", label: "Score rapprochement automatique", description: "Score minimal au-delà duquel l'écriture est rapprochée sans validation manuelle (DF-N1).", group: "logic", type: "number", min: 80, max: 100, roles: ["admin", "directeur", "comptable"] },
            { key: "dunning_delay_days", label: "Délai avant relance impayé (jours)", description: "Échéance d'envoi de première relance facture (DF-I2).", group: "logic", type: "number", min: 7, max: 90, roles: ["admin", "directeur", "comptable"] },
            { key: "payout_approval_threshold_eur", label: "Seuil approbation virement (€)", description: "Plafond au-delà duquel une validation éditeur est requise (DF-I1).", group: "logic", type: "number", min: 100, max: 50000, roles: ["admin"] },
            { key: "expense_approval_threshold", label: "Seuil approbation dépenses (€)", group: "logic", type: "number", min: 50, max: 5000, roles: ["admin", "directeur"] },
            { key: "tips_distribution_method", label: "Méthode répartition pourboires", group: "logic", type: "select", options: [{ value: "equal", label: "Égale" }, { value: "hours", label: "Par heures" }, { value: "points", label: "Par points" }], roles: ["admin", "directeur"] },
        ],
    },
    analytics: {
        title: "Paramètres Analyses",
        settings: [
            { key: "default_period", label: "Période par défaut", group: "logic", type: "select", options: [{ value: "week", label: "Semaine" }, { value: "month", label: "Mois" }, { value: "quarter", label: "Trimestre" }], roles: ["admin", "directeur", "manager"] },
            { key: "compare_previous", label: "Comparer à", group: "logic", type: "select", options: [{ value: "previous", label: "Période précédente" }, { value: "year", label: "Année précédente" }], roles: ["admin", "directeur", "manager"] },
            { key: "auto_report_frequency", label: "Fréquence rapports auto", group: "logic", type: "select", options: [{ value: "none", label: "Aucun" }, { value: "daily", label: "Quotidien" }, { value: "weekly", label: "Hebdomadaire" }, { value: "monthly", label: "Mensuel" }], roles: ["admin", "directeur"] },
        ],
    },
    haccp: {
        title: "Paramètres HACCP & Hygiène",
        settings: [
            { key: "temp_check_frequency", label: "Fréquence relevés (h)", group: "logic", type: "number", min: 1, max: 12, roles: ["admin", "directeur"] },
            { key: "alert_delay_minutes", label: "Délai alerte (min)", group: "logic", type: "number", min: 5, max: 60, roles: ["admin", "directeur"] },
            { key: "photo_required", label: "Photo obligatoire NC", group: "style", type: "toggle", roles: ["admin", "directeur"] },
            { key: "signature_required", label: "Signature requise", group: "style", type: "toggle", roles: ["admin", "directeur"] },
            { key: "report_frequency", label: "Fréquence rapports", group: "logic", type: "select", options: [{ value: "daily", label: "Quotidien" }, { value: "weekly", label: "Hebdomadaire" }], roles: ["admin", "directeur"] },
            { key: "retention_years", label: "Rétention archives (ans)", group: "logic", type: "number", min: 1, max: 10, roles: ["admin"] },
            { key: "thaw_max_hold_hours", label: "Durée max après décongélation (h)", description: "Délai maximal de conservation des produits décongelés (DF-E3).", group: "logic", type: "number", min: 6, max: 96, roles: ["admin", "directeur", "chef_cuisinier"] },
            { key: "escalation_target", label: "Escalade non-conformité hygiène", description: "Destinataire de l'alerte en cas d'absence de réaction (DF-E2).", group: "logic", type: "select", options: [{ value: "chef", label: "Chef de cuisine" }, { value: "manager", label: "Gérant" }, { value: "both", label: "Les deux" }], roles: ["admin", "directeur"] },
            { key: "temp_max_meat", label: "Température max — viandes (°C)", description: "Plafond réglementaire sanitaire viandes (DF-E1).", group: "logic", type: "number", min: 0, max: 4, roles: ["admin", "directeur", "chef_cuisinier"] },
            { key: "temp_max_fish", label: "Température max — poissons & fruits de mer (°C)", description: "Plafond réglementaire sanitaire poissons (DF-E1).", group: "logic", type: "number", min: 0, max: 2, roles: ["admin", "directeur", "chef_cuisinier"] },
            { key: "temp_max_dairy", label: "Température max — produits laitiers (°C)", description: "Plafond réglementaire sanitaire crèmerie (DF-E1).", group: "logic", type: "number", min: 0, max: 8, roles: ["admin", "directeur", "chef_cuisinier"] },
        ],
    },
    groups: {
        title: "Paramètres Groupes",
        settings: [
            { key: "deposit_required", label: "Acompte requis", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "deposit_percent", label: "Acompte par défaut (%)", group: "logic", type: "number", min: 10, max: 100, roles: ["admin", "directeur"] },
        ],
    },
    seo: {
        title: "Paramètres SEO & Réputation",
        settings: [
            { key: "auto_check_frequency", label: "Fréquence vérification", group: "logic", type: "select", options: [{ value: "daily", label: "Quotidien" }, { value: "weekly", label: "Hebdomadaire" }], roles: ["admin", "directeur"] },
            { key: "review_bombing_burst_threshold", label: "Avis négatifs déclenchant alerte", description: "Seuil de détection d'attaque e-réputation (DF-L1).", group: "logic", type: "number", min: 3, max: 50, roles: ["admin", "directeur"] },
            { key: "review_bombing_no_text_ratio", label: "Part suspecte avis sans texte (%)", group: "logic", type: "number", min: 20, max: 100, roles: ["admin", "directeur"] },
        ],
    },
    bar: {
        title: "Paramètres Bar & Tireuses",
        settings: [
            { key: "sound_new_order", label: "Son nouvelle commande", group: "style", type: "toggle", roles: ["admin", "directeur", "manager"] },
            { key: "auto_print_ticket", label: "Impression auto ticket", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
            { key: "alcohol_loss_alert_eur", label: "Seuil alerte perte alcool (€)", description: "Seuil d'écart financier déclenchant une alerte inventaire bar (DF-A3).", group: "logic", type: "number", min: 1, max: 500, roles: ["admin", "directeur", "manager", "barman"] },
            { key: "spout_variance_cl", label: "Écart toléré bec verseur (cl)", description: "Tolérance télémétrique par dose servie SmartSpout (DF-A4).", group: "logic", type: "number", min: 1, max: 50, roles: ["admin", "directeur", "manager", "barman"] },
            { key: "keg_loss_max_pct", label: "Perte fût maximale acceptée (%)", description: "Coefficient de perte hydrostatique sur fût (DF-A5).", group: "logic", type: "number", min: 0, max: 30, roles: ["admin", "directeur", "barman"] },
        ],
    },
    registre: {
        title: "Paramètres Registres",
        settings: [
            { key: "retention_years", label: "Rétention archives (ans)", group: "logic", type: "number", min: 1, max: 10, roles: ["admin", "directeur"] },
            { key: "auto_export", label: "Export automatique", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
        ],
    },
    workshop: {
        title: "Paramètres Atelier & Baies",
        settings: [
            { key: "auto_schedule_technician", label: "Assignation automatique technicien", group: "logic", type: "toggle", roles: ["admin", "directeur", "manager"] },
        ],
    },
    consultations: {
        title: "Paramètres Consultations & Actes",
        settings: [
            { key: "ccam_teletransmission", label: "Télétransmission SESAM-Vitale", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
        ],
    },
    vault: {
        title: "Paramètres Chambre Forte & Scellés",
        settings: [
            { key: "nfc_double_custody", label: "Double authentification scellé NFC", group: "logic", type: "toggle", roles: ["admin", "directeur"] },
        ],
    },
    settings: {
        title: "Paramètres Système",
        settings: [], // Settings page has its own interface
    },
};
