// @ts-nocheck
import { runProtocolOverload } from '../tests/benchmarks/StressTestRush';
import { fleetEngine } from '../src/lib/nexus/NexusFleetEngine';
import { MacroBrain } from '../src/domain/services/MacroBrain';
import * as fs from 'fs';
import * as path from 'path';

/**
 * 👑 STRESS TEST ORCHESTRATOR - Protocol OVERLOAD & ORACLE
 * Coordinates the full validation cycle of Phase 16.
 */

function loadEnv() {
    const envPath = path.join(__dirname, '../.env.local');
    if (fs.existsSync(envPath)) {
        const envContent = fs.readFileSync(envPath, 'utf-8');
        envContent.split('\n').forEach(line => {
            const trimmed = line.trim();
            if (trimmed && !trimmed.startsWith('#') && trimmed.includes('=')) {
                const parts = trimmed.split('=');
                const key = parts[0].trim();
                const value = parts.slice(1).join('=').replace(/^["']|["']$/g, '').trim();
                process.env[key] = value;
            }
        });
        console.log(`📝 Loaded .env.local variables. Project: ${process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID}`);
    }
}


async function main() {
    loadEnv();
    console.log("🌌 Starting Protocol : OVERLOAD & ORACLE");


    try {
        // 1. EXECUTE STRESS TEST
        // This will fire 50 orders and return metrics
        const metrics = await runProtocolOverload();

        if (metrics.successRate < 100) {
            console.error(`🛑 STRESS TEST FAILED : Success Rate ${metrics.successRate}%`);
            // We continue for diagnostic purposes as per user request
        }

        // 2. QUERY FLEET ENGINE
        // Generate insights based on the new rush data
        console.log("\n🛰️  Querying NexusFleetEngine for post-rush telemetry...");
        // We simulate fetching instances. In production, this pulls from Firestore.
        const mockInstances: any[] = [
            {
                id: 'stress_test_tenant',
                name: 'Stress Test Node',
                metrics: {
                    dailyRevenue: metrics.orderCount * 15,
                    healthScore: metrics.successRate,
                    lowStockAlerts: 3, // Pain, Steak, Fromage should be low now
                    activeUsers: 1
                }
            }
        ];

        const { insights } = await fleetEngine.updateFleetIntelligence(mockInstances);
        console.log(`📍 Nexus insights generated: ${insights.length}`);

        // 3. CALL THE ORACLE (Gemini)
        console.log("\n🔮 Invoking the Oracle for Strategic Audit...");
        const oraclePrompt = `Basé sur ce rush artificiel de ${metrics.orderCount} commandes (Taux succès: ${metrics.successRate}%, Latence: ${metrics.avgLatency.toFixed(2)}ms), quel est l'impact théorique sur ma marge brute et quel ingrédient dois-je recommander en priorité d'ici 24h ?`;
        
        const oracleInsight = await MacroBrain.getOracleAudit(oraclePrompt, { metrics, insights });
        
        console.log("\n--- 📜 ORACLE RESPONSE ---");
        console.log(oracleInsight);

        // 4. UPDATE HUD (CDC_DATA.js)
        console.log("\n🖥️  Updating HUD : scripts/CDC_DATA.js");
        const cdcDataPath = path.join(__dirname, 'CDC_DATA.js');
        
        // Calculate Velocity Score : (Orders / Total Duration) * Integrity Weight
        const velocityScore = Math.round((metrics.orderCount / (metrics.totalDuration / 1000)) * 100);

        const cdcContent = `// 🌌 CDC - COMMANDER DATA CENTER
// Auto-generated by Antigravity Stress Test Protocol
export const CDC_SNAPSHOT = {
    velocityScore: ${velocityScore},
    activeNodes: 1,
    lastUpdate: "${new Date().toISOString()}",
    oracleInsight: ${JSON.stringify(oracleInsight)},
    metrics: ${JSON.stringify(metrics, null, 2)}
};
`;

        fs.writeFileSync(cdcDataPath, cdcContent);
        console.log(`✅ HUD Updated. Velocity Score : ${velocityScore}`);

        console.log("\n✨ PROTOCOL COMPLETED SUCCESSFULLY.");

    } catch (error) {
        console.error("💥 Protocol Failure:", error);
        process.exit(1);
    }
}

main();
