import React, { useState } from 'react';

interface AIPatch {
  id: string;
  ticketId: string;
  description: string;
  codeDiff: string;
  confidenceScore: number;
  status: 'PENDING' | 'DEPLOYED' | 'REJECTED';
}

export const AIWorkshop: React.FC = () => {
  const [patches, setPatches] = useState<AIPatch[]>([]);

  const handleDeployPatch = (patchId: string) => {
    setPatches(currentPatches =>
      currentPatches.map(patch =>
        patch.id === patchId ? { ...patch, status: 'DEPLOYED' } : patch
      )
    );
  };

  const handleRejectPatch = (patchId: string) => {
    setPatches(currentPatches =>
      currentPatches.map(patch =>
        patch.id === patchId ? { ...patch, status: 'REJECTED' } : patch
      )
    );
  };

  return (
    <div className="p-6 bg-surface-sidebar text-white rounded-lg shadow-xl">
      <h2 className="text-2xl font-bold mb-4 text-brand">MCC AI Workshop</h2>
      <p className="mb-6 text-muted">Validate and deploy neural patches generated by NAM.</p>

      <div className="space-y-4">
        {patches.length === 0 ? (
          <p className="text-secondary italic">No pending AI patches in queue.</p>
        ) : (
          patches.map(patch => (
            <div key={patch.id} className="border border-default p-4 rounded bg-surface-sidebar">
              <div className="flex justify-between items-center mb-2">
                <h3 className="text-lg font-semibold text-status-success">Patch #{patch.id}</h3>
                <span className="text-sm bg-action-primary text-brand py-1 px-2 rounded">
                  Confidence: {(patch.confidenceScore * 100).toFixed(0)}%
                </span>
              </div>
              <p className="text-sm text-muted mb-2">Ticket ID: {patch.ticketId}</p>
              <p className="mb-4">{patch.description}</p>
              <pre className="bg-surface-sidebar p-3 rounded text-xs text-status-success overflow-x-auto mb-4">
                {patch.codeDiff}
              </pre>
              <div className="flex space-x-3">
                <button
                  onClick={() => handleDeployPatch(patch.id)}
                  disabled={patch.status !== 'PENDING'}
                  className="bg-status-success hover:bg-status-success px-4 py-2 rounded font-bold disabled:opacity-50"
                >
                  DEPLOY PATCH
                </button>
                <button
                  onClick={() => handleRejectPatch(patch.id)}
                  disabled={patch.status !== 'PENDING'}
                  className="bg-status-danger hover:bg-status-danger px-4 py-2 rounded font-bold disabled:opacity-50"
                >
                  REJECT
                </button>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};
