export {  AI_MODELS  } from '@_modules/intelligence/ia/ai'; // @nexus-legacy;
export type {  TenantRBACConfig  } from '@_modules/human'; // @nexus-legacy;
export type {  PlatformVariant  } from '@_modules/system'; // @nexus-legacy;
export {  GeminiProvider  } from '@_modules/intelligence/ia/GeminiProvider'; // @nexus-legacy;
export {  TelemetryEvent  } from '@_modules/intelligence/analytique/TelemetryStream'; // @nexus-legacy;
export {  HACCPTelemetryBridge  } from '@_modules/compliance/qualite/haccp/services/HACCPTelemetryBridge'; // @nexus-legacy;
export {  fleetEngine  } from '@_modules/intelligence/ia/fleet/FleetAdapter'; // @nexus-legacy;
export {  TelemetryStream  } from '@_modules/intelligence/analytique/TelemetryStream'; // @nexus-legacy;
export type {  TenantConfig  } from '@_modules/system'; // @nexus-legacy;
export type {  OrchestratorSignal  } from '@_modules/system'; // @nexus-legacy;
export type {  TenantTheme  } from '@_modules/system'; // @nexus-legacy;
export type {  ProviderCatalogEntry  } from '@_modules/human'; // @nexus-legacy;
export {  UniversalImportDropzone  } from '@_modules/commerce/acquisition/onboarding'; // @nexus-legacy;
export {  OnboardingProgress  } from '@_modules/commerce/acquisition/onboarding'; // @nexus-legacy;
export {  CATEGORY_CONFIGS  } from '@_modules/commerce/acquisition/onboarding'; // @nexus-legacy;
export type {  ImportCategory  } from '@_modules/commerce/acquisition/onboarding'; // @nexus-legacy;
export {  EmbedSnippets  } from '@_modules/commerce'; // @nexus-legacy;
export {  ROICalculator  } from '@_modules/commerce'; // @nexus-legacy;
export {  OnlineBookingToggle  } from '@_modules/commerce'; // @nexus-legacy;
export {  AmbianceService  } from '@_modules/facility/spaces/AmbianceService'; // @nexus-legacy;
export {  RestaurantAmbiance  } from '@_modules/facility/spaces/AmbianceService'; // @nexus-legacy;
export type {  ImportCategory  } from '@_modules/commerce/acquisition/onboarding/migration/types'; // @nexus-legacy;
export type {  ConnectorId  } from '@_modules/commerce/acquisition/onboarding/migration/connectors/types'; // @nexus-legacy;
export {  CartLineSchema  } from '@_modules/ops/domain/schemas/pos'; // @nexus-legacy;
export {  CartLine  } from '@_modules/ops/domain/schemas/pos'; // @nexus-legacy;
export {  PosTicket  } from '@_modules/ops/domain/schemas/pos'; // @nexus-legacy;
export {  PosTicketSchema  } from '@_modules/ops/domain/schemas/pos'; // @nexus-legacy;
export {  TenantConfigSchema  } from '@_modules/system/domain/schemas/tenant'; // @nexus-legacy;
export {  type TenantConfig  } from '@_modules/system/domain/schemas/tenant'; // @nexus-legacy;
export {  UserSchema  } from '@_modules/human/domain/schemas/users'; // @nexus-legacy;
export {  type User  } from '@_modules/human/domain/schemas/users'; // @nexus-legacy;
export {  ChaosMonkey  } from '@_modules/intelligence/ia/resilience/ChaosMonkey'; // @nexus-legacy;
export {  ResilienceSlayer  } from '@_modules/intelligence/ia/resilience/ResilienceSlayer'; // @nexus-legacy;
export type {  User  } from '@_modules/human'; // @nexus-legacy;
export {  FleetCommander  } from '@_modules/intelligence/ia/fleet/FleetCommander'; // @nexus-legacy;
export {  HermesEngine  } from '@_modules/intelligence'; // @nexus-legacy;
export {  type HermesPulseResult  } from '@_modules/intelligence'; // @nexus-legacy;
export type {  SimulationMetrics  } from '@_modules/intelligence'; // @nexus-legacy;
export {  simulator  } from '@_modules/intelligence'; // @nexus-legacy;
export {  simulationMetricsAtom  } from '@_modules/intelligence'; // @nexus-legacy;
export {  isSimulationRunningAtom  } from '@_modules/intelligence'; // @nexus-legacy;
export {  type SimulationProfile  } from '@_modules/intelligence'; // @nexus-legacy;
export {  SovereignLedger  } from '@_modules/finance/tresorerie/SovereignLedgerAdapter'; // @nexus-legacy;
export {  QuantumOrchestrator  } from '@_modules/intelligence/ia/fleet/QuantumOrchestrator'; // @nexus-legacy;
export {  ConnectorHub  } from '@_modules/intelligence/connectors/hub'; // @nexus-legacy;
export type {  CommunicationPulse  } from '@_modules/finance/tresorerie/collection/types'; // @nexus-legacy;
export {  fleetTelemetry  } from '@_modules/intelligence'; // @nexus-legacy;
export {  sovereignCreateWorkspace  } from '@_modules/intelligence'; // @nexus-legacy;
export {  AuditLogger  } from '@_modules/compliance/securite/AuditLogger'; // @nexus-legacy;
export type {  Floor  } from '@_modules/ops'; // @nexus-legacy;
export type {  Zone  } from '@_modules/ops'; // @nexus-legacy;
export type {  Table  } from '@_modules/ops'; // @nexus-legacy;
export {  FiscalKeyService  } from '@_modules/finance/services/FiscalKeyService'; // @nexus-legacy;
export {  fiscalLedgerAtom  } from '@_modules/compliance/qualite/haccp/store/complianceAtoms'; // @nexus-legacy;
export {  simulatorDb  } from '@_modules/intelligence/ia/simulator/SimulatorDB'; // @nexus-legacy;
export {  IdentityExtractionSchema  } from '@_modules/compliance'; // @nexus-legacy;
export {  ComplianceExtractionErrorSchema  } from '@_modules/compliance'; // @nexus-legacy;
export {  type IdentityExtraction  } from '@_modules/compliance'; // @nexus-legacy;
export {  type ComplianceExtractionError  } from '@_modules/compliance'; // @nexus-legacy;
export {  ImmunityAuditLogger  } from '@_modules/compliance/securite/ImmunityAuditLogger'; // @nexus-legacy;
export {  OpsSyncService  } from '@_modules/ops/workflow/engine/ops.sync'; // @nexus-legacy;
export {  InventorySyncService  } from '@_modules/logistics/stock/inventory/inventory.sync'; // @nexus-legacy;
export {  HACCPSyncService  } from '@_modules/compliance/qualite/haccp/haccp.sync'; // @nexus-legacy;
export {  MarketingSyncService  } from '@_modules/commerce/acquisition/marketing/marketing.sync'; // @nexus-legacy;
export {  HRSyncService  } from '@_modules/human/effectifs/hr/hr.sync'; // @nexus-legacy;
export type {  InvoiceTarget  } from '@_modules/finance'; // @nexus-legacy;

export * from '@/modules/ops';
export * from '@/modules/X';
export * from '@/modules/compliance/qualite/haccp/types';
export * from '@/modules/intelligence/analytique/store/dashboardAtoms';
export * from '@/modules/facility/spaces/settings/store/settingsAtoms';
