// @ts-nocheck
import { PageKey, PageSettingConfig } from "@/types/permissions.types";

export const PAGE_SETTINGS: Record<PageKey, { title: string; settings: PageSettingConfig[] }> = {
    dashboard: {
        title: "Paramètres du Tableau de Bord",
        settings: [
            { key: "show_ca", label: "Afficher le CA", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "period_default", label: "Période par défaut", group: "logic", type: "select", options: [{ value: "day", label: "Jour" }, { value: "week", label: "Semaine" }, { value: "month", label: "Mois" }], roles: ["super_admin", "directeur", "manager"] },
            { key: "ca_target", label: "Objectif CA journalier (€)", group: "logic", type: "number", min: 0, max: 100000, roles: ["super_admin", "directeur"] },
            { key: "tickets_target", label: "Objectif tickets/jour", group: "logic", type: "number", min: 0, max: 500, roles: ["super_admin", "directeur"] },
            { key: "occupation_target", label: "Objectif occupation (%)", group: "logic", type: "number", min: 0, max: 100, roles: ["super_admin", "directeur"] },
            { key: "show_staff_metrics", label: "Afficher métriques équipe", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "show_weather_widget", label: "Afficher météo", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager", "serveur", "hotesse"] },
            { key: "auto_refresh_interval", label: "Rafraîchissement auto (sec)", group: "logic", type: "number", min: 10, max: 300, roles: ["super_admin", "directeur", "manager"] },
            { key: "show_reservations_preview", label: "Aperçu réservations à venir", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "manager", "hotesse"] },
        ],
    },
    floor_plan: {
        title: "Paramètres du Plan de Salle",
        settings: [
            { key: "show_grid", label: "Afficher la grille", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "grid_size", label: "Taille de grille", group: "style", type: "select", options: [{ value: "20", label: "20px" }, { value: "40", label: "40px" }, { value: "60", label: "60px" }], roles: ["super_admin", "directeur"] },
            { key: "snap_to_grid", label: "Alignement grille", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "default_view", label: "Vue par défaut", group: "style", type: "select", options: [{ value: "2d", label: "2D" }, { value: "3d", label: "3D" }], roles: ["super_admin", "directeur", "manager"] },
            { key: "lock_zones", label: "Verrouiller les zones", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "table_numbering_auto", label: "Numérotation auto tables", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "show_server_zones", label: "Afficher zones serveurs", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "show_capacity_limits", label: "Afficher limites capacité", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "edit_mode_locked", label: "Verrouiller mode édition", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
        ],
    },
    reservations: {
        title: "Paramètres des Réservations",
        settings: [
            { key: "default_view", label: "Vue par défaut", group: "style", type: "select", options: [{ value: "day", label: "Jour" }, { value: "week", label: "Semaine" }, { value: "list", label: "Liste" }], roles: ["super_admin", "directeur", "manager", "hotesse"] },
            { key: "default_duration", label: "Durée par défaut (min)", group: "logic", type: "select", options: [{ value: "60", label: "60 min" }, { value: "90", label: "90 min" }, { value: "120", label: "120 min" }], roles: ["super_admin", "directeur"] },
            { key: "min_advance", label: "Délai min avant résa (h)", group: "logic", type: "number", min: 0, max: 48, roles: ["super_admin", "directeur"] },
            { key: "max_advance", label: "Délai max avant résa (j)", group: "logic", type: "number", min: 1, max: 90, roles: ["super_admin", "directeur"] },
            { key: "auto_confirm", label: "Confirmation automatique", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "allow_overbooking", label: "Autoriser l'overbooking", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "noshow_delay", label: "Délai no-show (min)", group: "logic", type: "number", min: 5, max: 60, roles: ["super_admin", "directeur", "manager"] },
            { key: "sms_confirmation", label: "Confirmation par SMS", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "email_confirmation", label: "Confirmation par email", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "reminder_hours_before", label: "Rappel X heures avant", group: "logic", type: "number", min: 1, max: 48, roles: ["super_admin", "directeur"] },
            { key: "vip_priority", label: "Réservation VIP prioritaire", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "auto_assign_tables", label: "Attribution auto tables", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "waitlist_enabled", label: "Liste d'attente activée", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
        ],
    },
    pos: {
        title: "Paramètres de la Caisse",
        settings: [
            { key: "service_mode", label: "Mode service", group: "logic", type: "select", options: [{ value: "table", label: "Table" }, { value: "counter", label: "Comptoir" }, { value: "mixed", label: "Mixte" }], roles: ["super_admin", "directeur"] },
            { key: "button_size", label: "Taille des boutons", group: "style", type: "select", options: [{ value: "small", label: "Petit" }, { value: "medium", label: "Moyen" }, { value: "large", label: "Grand" }], roles: ["super_admin", "directeur", "manager"] },
            { key: "show_images", label: "Afficher les images", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "auto_print", label: "Impression auto ticket", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "tips_enabled", label: "Pourboires activés", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "sound_enabled", label: "Sons activés", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "max_discount_no_pin", label: "Remise max sans code (%)", group: "logic", type: "number", min: 0, max: 50, roles: ["super_admin", "directeur"] },
            { key: "split_bill_enabled", label: "Addition divisée", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "quick_pay_buttons", label: "Boutons paiement rapide", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "cash_drawer_auto_open", label: "Ouverture auto caisse", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "require_table_selection", label: "Table obligatoire", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "show_stock_level", label: "Afficher niveau stock", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "keyboard_shortcuts", label: "Raccourcis clavier", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "loyalty_points_visible", label: "Points fidélité visibles", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
        ],
    },
    kitchen: {
        title: "Paramètres Cuisine & Recettes",
        settings: [
            { key: "default_unit", label: "Unité par défaut", group: "logic", type: "select", options: [{ value: "g", label: "Grammes" }, { value: "kg", label: "Kilos" }, { value: "L", label: "Litres" }, { value: "portions", label: "Portions" }], roles: ["super_admin", "directeur", "chef_cuisinier"] },
            { key: "default_yield", label: "Rendement par défaut", group: "logic", type: "number", min: 1, max: 100, roles: ["super_admin", "directeur", "chef_cuisinier"] },
            { key: "show_costs_to_cooks", label: "Afficher coûts aux cuisiniers", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "show_margins", label: "Afficher les marges", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "default_waste_percent", label: "% perte par défaut", group: "logic", type: "number", min: 0, max: 50, roles: ["super_admin", "directeur", "chef_cuisinier"] },
            { key: "show_nutrition", label: "Afficher nutrition", group: "style", type: "toggle", roles: ["super_admin", "directeur", "chef_cuisinier"] },
            { key: "show_allergens", label: "Afficher allergènes", group: "style", type: "toggle", roles: ["super_admin", "directeur", "chef_cuisinier"] },
            { key: "target_food_cost", label: "% food cost cible", group: "logic", type: "number", min: 10, max: 60, roles: ["super_admin", "directeur"] },
            { key: "recipe_scaling_enabled", label: "Mise à l'échelle recettes", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "chef_cuisinier"] },
            { key: "ingredient_substitution_alerts", label: "Alertes substitution ingrédients", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "chef_cuisinier"] },
            { key: "batch_cooking_mode", label: "Mode production par lots", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "chef_cuisinier"] },
            { key: "print_recipe_cards", label: "Impression fiches recettes", group: "style", type: "toggle", roles: ["super_admin", "directeur", "chef_cuisinier"] },
            { key: "plating_guides", label: "Guides de dressage", group: "style", type: "toggle", roles: ["super_admin", "directeur", "chef_cuisinier"] },
        ],
    },
    kds: {
        title: "Paramètres KDS",
        settings: [
            { key: "columns", label: "Nombre de colonnes", group: "style", type: "select", options: [{ value: "2", label: "2" }, { value: "3", label: "3" }, { value: "4", label: "4" }, { value: "5", label: "5" }], roles: ["super_admin", "directeur", "manager"] },
            { key: "sort_mode", label: "Tri des commandes", group: "logic", type: "select", options: [{ value: "fifo", label: "FIFO" }, { value: "priority", label: "Priorité" }, { value: "type", label: "Type" }], roles: ["super_admin", "directeur", "manager"] },
            { key: "alert_delay", label: "Alerte retard (min)", group: "logic", type: "number", min: 5, max: 60, roles: ["super_admin", "directeur"] },
            { key: "sound_new_order", label: "Son nouvelle commande", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "sound_alert", label: "Son alerte retard", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "show_table", label: "Afficher table/client", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "highlight_allergies", label: "Signaler allergies", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "bump_confirmation", label: "Confirmation bump", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "order_age_colors", label: "Couleurs selon ancienneté", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "consolidate_items", label: "Regrouper items identiques", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "prep_time_estimates", label: "Estimation temps préparation", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "chef_cuisinier"] },
        ],
    },
    inventory: {
        title: "Paramètres Inventaire",
        settings: [
            { key: "low_stock_threshold", label: "Seuil stock bas", group: "logic", type: "number", min: 1, max: 100, roles: ["super_admin", "directeur", "manager"] },
            { key: "critical_threshold", label: "Seuil critique", group: "logic", type: "number", min: 1, max: 50, roles: ["super_admin", "directeur"] },
            { key: "default_unit", label: "Unité par défaut", group: "logic", type: "select", options: [{ value: "kg", label: "kg" }, { value: "L", label: "L" }, { value: "units", label: "Unités" }], roles: ["super_admin", "directeur", "manager"] },
            { key: "valuation_method", label: "Méthode valorisation", group: "logic", type: "select", options: [{ value: "fifo", label: "FIFO" }, { value: "lifo", label: "LIFO" }, { value: "weighted", label: "Moy. pondérée" }], roles: ["super_admin", "directeur"] },
            { key: "show_valuation", label: "Afficher valeur stock", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "auto_order_enabled", label: "Commande auto activée", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "supplier_comparison", label: "Comparaison fournisseurs", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "barcode_scanning", label: "Scan codes-barres", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "lot_tracking", label: "Traçabilité lots", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "expiry_first_out", label: "DLC prioritaire sortie", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "waste_tracking_mandatory", label: "Suivi pertes obligatoire", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "count_frequency_days", label: "Fréquence inventaire (jours)", group: "logic", type: "number", min: 1, max: 30, roles: ["super_admin", "directeur"] },
        ],
    },
    storage_map: {
        title: "Paramètres Stockage",
        settings: [
            { key: "dlc_alert_days", label: "Alerte DLC (jours avant)", group: "logic", type: "number", min: 1, max: 14, roles: ["super_admin", "directeur", "manager"] },
            { key: "compact_view", label: "Vue compacte", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "temperature_alerts", label: "Alertes température", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "zone_capacity_display", label: "Afficher capacité zones", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "fifo_enforcement", label: "Forcer FIFO", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
        ],
    },
    crm: {
        title: "Paramètres CRM",
        settings: [
            { key: "default_view", label: "Vue par défaut", group: "style", type: "select", options: [{ value: "list", label: "Liste" }, { value: "cards", label: "Cartes" }, { value: "table", label: "Tableau" }], roles: ["super_admin", "directeur", "manager"] },
            { key: "required_phone", label: "Téléphone obligatoire", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "required_email", label: "Email obligatoire", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "retention_months", label: "Rétention données (mois)", group: "logic", type: "number", min: 6, max: 120, roles: ["super_admin"] },
            { key: "vip_auto_upgrade", label: "Upgrade VIP auto", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "vip_threshold_visits", label: "Seuil visites VIP", group: "logic", type: "number", min: 1, max: 50, roles: ["super_admin", "directeur"] },
            { key: "vip_threshold_spend", label: "Seuil dépenses VIP (€)", group: "logic", type: "number", min: 100, max: 10000, roles: ["super_admin", "directeur"] },
            { key: "birthday_reminders", label: "Rappels anniversaires", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "feedback_request_enabled", label: "Demande feedback auto", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "gdpr_consent_required", label: "Consentement RGPD requis", group: "logic", type: "toggle", roles: ["super_admin"] },
        ],
    },
    staff: {
        title: "Paramètres Équipe",
        settings: [
            { key: "show_salaries_to_managers", label: "Salaires visibles aux managers", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "doc_expiry_alert_days", label: "Alerte expiration docs (jours)", group: "logic", type: "number", min: 7, max: 90, roles: ["super_admin", "directeur"] },
            { key: "timesheet_approval_required", label: "Approbation pointages", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "overtime_auto_calculate", label: "Calcul auto heures sup", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "photo_id_required", label: "Photo ID obligatoire", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "skills_matrix_enabled", label: "Matrice compétences", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "performance_reviews_enabled", label: "Évaluations performance", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "training_tracking", label: "Suivi formations", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "contract_alerts", label: "Alertes contrats", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
        ],
    },
    planning: {
        title: "Paramètres Planning",
        settings: [
            { key: "week_start", label: "Premier jour semaine", group: "logic", type: "select", options: [{ value: "monday", label: "Lundi" }, { value: "sunday", label: "Dimanche" }], roles: ["super_admin", "directeur"] },
            { key: "default_view", label: "Vue par défaut", group: "style", type: "select", options: [{ value: "day", label: "Jour" }, { value: "week", label: "Semaine" }, { value: "month", label: "Mois" }], roles: ["super_admin", "directeur", "manager"] },
            { key: "max_hours_day", label: "Max heures/jour", group: "logic", type: "number", min: 6, max: 12, roles: ["super_admin", "directeur"] },
            { key: "max_hours_week", label: "Max heures/semaine", group: "logic", type: "number", min: 20, max: 48, roles: ["super_admin", "directeur"] },
            { key: "min_rest_hours", label: "Repos min entre shifts (h)", group: "logic", type: "number", min: 8, max: 14, roles: ["super_admin", "directeur"] },
            { key: "notify_on_publish", label: "Notifier à la publication", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "require_swap_approval", label: "Valider les échanges", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "overtime_enabled", label: "Heures sup autorisées", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "auto_schedule_enabled", label: "Planification auto (IA)", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "availability_required", label: "Disponibilités obligatoires", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "shift_templates", label: "Modèles de shifts", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "labor_cost_preview", label: "Aperçu coût main d'oeuvre", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "conflict_detection", label: "Détection conflits", group: "logic", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "mobile_clock_in", label: "Pointage mobile", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
        ],
    },
    leaves: {
        title: "Paramètres Congés",
        settings: [
            { key: "require_approval", label: "Approbation requise", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "min_advance_days", label: "Délai min demande (jours)", group: "logic", type: "number", min: 1, max: 30, roles: ["super_admin", "directeur"] },
            { key: "max_concurrent_leaves", label: "Max congés simultanés", group: "logic", type: "number", min: 1, max: 10, roles: ["super_admin", "directeur"] },
            { key: "blackout_dates_enabled", label: "Dates bloquées", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "auto_approve_short_leaves", label: "Auto-approbation congés courts", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "carry_over_days", label: "Report jours congés", group: "logic", type: "number", min: 0, max: 30, roles: ["super_admin", "directeur"] },
            { key: "sick_leave_certificate", label: "Justificatif maladie", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "leave_calendar_public", label: "Calendrier congés public", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
        ],
    },
    finance: {
        title: "Paramètres Finance",
        settings: [
            { key: "fiscal_year_start", label: "Début exercice fiscal", group: "logic", type: "text", roles: ["super_admin"] },
            { key: "default_payment_terms", label: "Conditions paiement (jours)", group: "logic", type: "number", min: 0, max: 90, roles: ["super_admin", "directeur", "comptable"] },
            { key: "invoice_prefix", label: "Préfixe factures", group: "logic", type: "text", roles: ["super_admin", "directeur"] },
            { key: "export_format", label: "Format export", group: "style", type: "select", options: [{ value: "pdf", label: "PDF" }, { value: "csv", label: "CSV" }, { value: "excel", label: "Excel" }], roles: ["super_admin", "directeur", "comptable"] },
            { key: "auto_invoice_generation", label: "Génération auto factures", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "bank_reconciliation_auto", label: "Rapprochement bancaire auto", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "expense_approval_threshold", label: "Seuil approbation dépenses (€)", group: "logic", type: "number", min: 50, max: 5000, roles: ["super_admin", "directeur"] },
            { key: "tips_distribution_method", label: "Méthode répartition pourboires", group: "logic", type: "select", options: [{ value: "equal", label: "Égale" }, { value: "hours", label: "Par heures" }, { value: "points", label: "Par points" }], roles: ["super_admin", "directeur"] },
        ],
    },
    analytics: {
        title: "Paramètres Analyses",
        settings: [
            { key: "default_period", label: "Période par défaut", group: "logic", type: "select", options: [{ value: "week", label: "Semaine" }, { value: "month", label: "Mois" }, { value: "quarter", label: "Trimestre" }], roles: ["super_admin", "directeur", "manager"] },
            { key: "compare_previous", label: "Comparer à", group: "logic", type: "select", options: [{ value: "previous", label: "Période précédente" }, { value: "year", label: "Année précédente" }], roles: ["super_admin", "directeur", "manager"] },
            { key: "auto_report_frequency", label: "Fréquence rapports auto", group: "logic", type: "select", options: [{ value: "none", label: "Aucun" }, { value: "daily", label: "Quotidien" }, { value: "weekly", label: "Hebdomadaire" }, { value: "monthly", label: "Mensuel" }], roles: ["super_admin", "directeur"] },
        ],
    },
    haccp: {
        title: "Paramètres HACCP",
        settings: [
            { key: "temp_check_frequency", label: "Fréquence relevés (h)", group: "logic", type: "number", min: 1, max: 12, roles: ["super_admin", "directeur"] },
            { key: "alert_delay_minutes", label: "Délai alerte (min)", group: "logic", type: "number", min: 5, max: 60, roles: ["super_admin", "directeur"] },
            { key: "photo_required", label: "Photo obligatoire NC", group: "style", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "signature_required", label: "Signature requise", group: "style", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "report_frequency", label: "Fréquence rapports", group: "logic", type: "select", options: [{ value: "daily", label: "Quotidien" }, { value: "weekly", label: "Hebdomadaire" }], roles: ["super_admin", "directeur"] },
            { key: "retention_years", label: "Rétention archives (ans)", group: "logic", type: "number", min: 1, max: 10, roles: ["super_admin"] },
        ],
    },
    groups: {
        title: "Paramètres Groupes",
        settings: [
            { key: "deposit_required", label: "Acompte requis", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
            { key: "deposit_percent", label: "Acompte par défaut (%)", group: "logic", type: "number", min: 10, max: 100, roles: ["super_admin", "directeur"] },
        ],
    },
    seo: {
        title: "Paramètres SEO",
        settings: [
            { key: "auto_check_frequency", label: "Fréquence vérification", group: "logic", type: "select", options: [{ value: "daily", label: "Quotidien" }, { value: "weekly", label: "Hebdomadaire" }], roles: ["super_admin", "directeur"] },
        ],
    },
    bar: {
        title: "Paramètres Bar",
        settings: [
            { key: "sound_new_order", label: "Son nouvelle commande", group: "style", type: "toggle", roles: ["super_admin", "directeur", "manager"] },
            { key: "auto_print_ticket", label: "Impression auto ticket", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
        ],
    },
    registre: {
        title: "Paramètres Registres",
        settings: [
            { key: "retention_years", label: "Rétention archives (ans)", group: "logic", type: "number", min: 1, max: 10, roles: ["super_admin", "directeur"] },
            { key: "auto_export", label: "Export automatique", group: "logic", type: "toggle", roles: ["super_admin", "directeur"] },
        ],
    },
    settings: {
        title: "Paramètres Système",
        settings: [], // Settings page has its own interface
    },
};
